apiVersion: v1
kind: ReplicationController
metadata: 
  labels:
    app: redis
    role: master
  name: redis-master
  namespace: default
spec: 
    replicas: 1
    selector: 
        app: redis
        role: master
    template: 
        metadata: 
            labels: 
                app: redis
                role: master
        spec: 
            containers: 
            - name: redis-master
              image: redis:2.8.23
            ports: 
            - name: redis-server
              containerPort: 6379
---
apiVersion: v1
kind: Service
metadata: 
    name: redis-master
    labels: 
        app: redis
        role: master
spec: 
    ports: 
        - port: 6379
          targetPort: redis-server
    selector: 
        app: redis
        role: master
---
apiVersion: v1
kind: ReplicationController
metadata: 
  labels:
    app: redis
    role: slave
  name: redis-slave
  namespace: default
spec: 
    replicas: 1
    selector: 
        app: redis
        role: slave
    template: 
        metadata: 
            labels: 
                app: redis
                role: slave
        spec: 
            containers: 
            - name: redis-slave
              image: redis:2.8.23
            ports: 
            - name: redis-server
              containerPort: 6379
---
apiVersion: v1
kind: Service
metadata: 
    name: redis-slave
    labels: 
        app: redis
        role: slave
spec: 
    ports: 
        - port: 6379
          targetPort: redis-server
    selector: 
        app: redis
        role: slave
---
apiVersion: v1
kind: ReplicationController
metadata: 
    name: guestbook
    labels: 
        app: guestbook
spec: 
 replicas: 3
 selector: 
    app: guestbook
 template: 
  metadata: 
   labels: 
    app: guestbook
  spec: 
   containers: 
    - 
   name: guestbook
     image: k8s.gcr.io/guestbook:v3
     ports: 
      - 
   name: http-server
       containerPort: 3000
---
apiVersion: v1
kind: Service
metadata: 
    name: guestbook
    labels: 
        app: guestbook
spec: 
    ports: 
        - port: 3000
          targetPort: http-server
    selector: 
        app: guestbook
        type: LoadBalancer